version: '3.8'

services:
  test:
    build: 
      context: .
      target: dev
    image: alereca/universiteams:1.0
    env_file:
      - docker.test.env
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app/src
      - ./test:/home/node/app/test
    ports:
      # Only for local debugging purposes
      - 9228:9229
    depends_on:
      - postgrestest
      - redistest
  postgrestest:
    image: postgres:12.8-alpine
    env_file:
      - docker.test.env
    ports:
      - 5432      
  redistest:
    image: redis:alpine
    ports:
      - 6379
