version: '3.8'

services:
  app:
    build: .
    ports:
      - 3000:3000
    command: npm run start:dev
    working_dir: /usr/src/app
    volumes: 
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
