version: '3.8'

services:
  app:
    build: 
      context: .
      target: dev
    image: alereca/universiteams:1.0
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app/src
      - ./test:/home/node/app/test
      - ./dist:/home/node/app/dist
    env_file:
      - docker.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12.8-alpine
    # Currently there is no need to expose this container port to host, since every interaction happens between containers
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker.env
  # Pg-admin won't be used in production
  pg-admin:
    image: dpage/pgadmin4:5.6
    ports:
      - 8080:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      - PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
  redis:
    image: redis:alpine
    ports:
      - 6379

volumes:
  pgdata:
  pgadmindata:
