version: '3.8'

services:
  test:
    build: .
    image: alereca/universiteams:1.0
    environment:
      POSTGRES_HOST: postgrestest
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgrestest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      ACCESS_TOKEN_SECRET: "access_token_test_secret"
      REFRESH_TOKEN_SECRET: "refresh_token_test_secret"
      EMAIL_VERIFICATION_LINK_SECRET: "verification_link_secret"
      FORGET_PASSWORD_VERIFICATION_LINK_SECRET: "forget_password_verification_link_secret"
      EMAIL_USER: "universe@example.com"
      EMAIL_CONFIRMATION_URL: "http://localhost:5000/account/verify"
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    ports:
      - 9228:9229
    depends_on:
      - postgrestest
  postgrestest:
    image: postgres:12.8-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgrestest
