export enum SecretsVaultKeys {
  ENV = 'NODE_ENV',
  ACCESS_TOKEN = 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN = 'REFRESH_TOKEN_SECRET',
  VERIFICATION_LINK_SECRET = 'VERIFICATION_LINK_SECRET',
  EMAIL_USER = 'EMAIL_USER',
}
