export enum SecretsVaultKeys {
  ENV = 'NODE_ENV',
  ACCESS_TOKEN = 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN = 'REFRESH_TOKEN_SECRET',
  EMAIL_CONFIRMATION_URL = 'EMAIL_CONFIRMATION_URL',
  EMAIL_VERIFICATION_LINK_SECRET = 'EMAIL_VERIFICATION_LINK_SECRET',
  FORGET_PASSWORD_VERIFICATION_LINK_SECRET = 'FORGET_PASSWORD_VERIFICATION_LINK_SECRET',
  FORGET_PASSWORD_URL = 'FORGET_PASSWORD_URL',
  EMAIL_USER = 'EMAIL_USER',
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  SENDINBLUE_API_KEY = 'SENDINBLUE_API_KEY',
  SAME_SITE_POLICY = 'SAME_SITE_POLICY',
  SECURE_COOKIE = 'SECURE_COOKIE',
}
